---
- name: just for practice purpose ok
  hosts: all
  tasks:
     - name: download jenkins file
       get_url:
          url: https://get.jenkins.io/war-stable/2.332.2/jenkins.war
          dest: /home/ubuntu
       tags: ani 
     - name: Pause
       pause:
        minutes: 1
       tags: ani1
     - name: fetch module copy from MN to Ansible
       fetch:
          src: jenkins.war
          dest: /tmp
       tags: ani2
     - name: copying from ansible to MN
       copy:
          src: /tmp/172.31.6.175
          dest: /home/ubuntu/takeitBro2
       tags: ani3
     - name: clonning work via git
       git:
          repo: https://github.com/SAGARSGS/git2.git
          dest: /tmp/justgit
       tags: ani4
     - name: file creating
       file:
          name: /home/ubuntu/ramesh
          state: touch
          owner: ubuntu
          group: root
          mode: 642
       tags: ani5
     - name: directory creating
       file:
          name: /home/ubuntu/dir1
          state: directory
          owner: ubuntu
          group: root
          mode: 642
       tags: ani6
     - name: deleying file with name of ramesh
       file:
          name: /home/ubuntu/ramesh
          state: absent
       tags: ani7
     - name: user creation with name of Pandu
       user:
          name: /home/ubuntu/Pandu
          password: sagarbhai
       tags: ani8
...

